
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def nextPage():
    window.destroy()
    import exam

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1531x828")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 828,
    width = 1531,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1531.0,
    828.0,
    fill="#023E8A",
    outline="")

canvas.create_rectangle(
    228.0,
    41.0,
    1304.0,
    828.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    648.0,
    41.0,
    anchor="nw",
    text="Course name",
    fill="#000000",
    font=("Satisfy Regular", 64 * -1)
)

canvas.create_text(
    242.0,
    304.0,
    anchor="nw",
    text="Please make sure you have all what you want in exam before starting, be ware that using the mobile illegal.  ",
    fill="#000000",
    font=("Satisfy Regular", 26 * -1)
)

canvas.create_text(
    246.0,
    361.0,
    anchor="nw",
    text="Exam time : 1 hour",
    fill="#000000",
    font=("Satisfy Regular", 26 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("bef_button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=nextPage,
    relief="flat"
)
button_1.place(
    x=717.0,
    y=711.0,
    width=170.0,
    height=111.0
)
window.resizable(False, False)
window.mainloop()
