
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

def nextPage():
    window.destroy()
    import Dashboard_student


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1531x828")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 828,
    width = 1531,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1531.0,
    828.0,
    fill="#023E8A",
    outline="")

canvas.create_rectangle(
    227.9999999999999,
    41.00000000000006,
    1304.0,
    828.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    647.9999999999999,
    41.00000000000006,
    anchor="nw",
    text="EXAM",
    fill="#000000",
    font=("Satisfy Regular", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("exam_button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=nextPage,
    relief="flat"
)
button_1.place(
    x=1359.0,
    y=701.0,
    width=163.0,
    height=99.0
)
window.resizable(False, False)
window.mainloop()
