
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from accounts_data import Database

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

def nextPage():
    window.destroy()
    import Dashboard

window.geometry("1531x828")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 828,
    width = 1531,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1531.0,
    828.0,
    fill="#023E8A",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("up_image_1.png"))
image_1 = canvas.create_image(
    166.0,
    152.0,
    image=image_image_1
)

canvas.create_text(
    56.0,
    309.0,
    anchor="nw",
    text="BirdEye",
    fill="#FFFFFF",
    font=("Satisfy Regular", 64 * -1)
)

canvas.create_text(
    359.0,
    358.0,
    anchor="nw",
    text="PASSWORD",
    fill="#FFFFFF",
    font=("Montserrat Light", 24 * -1)
)

canvas.create_text(
    362.0,
    452.0,
    anchor="nw",
    text="CONFIRM",
    fill="#FFFFFF",
    font=("Montserrat Light", 24 * -1)
)

canvas.create_text(
    359.0,
    257.0,
    anchor="nw",
    text="USERNAME",
    fill="#FFFFFF",
    font=("Montserrat Light", 24 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("up_image_2.png"))
image_2 = canvas.create_image(
    513.0,
    370.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("up_image_3.png"))
image_3 = canvas.create_image(
    505.0,
    465.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("up_button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=nextPage,
    relief="flat"
)
button_1.place(
    x=556.0,
    y=556.0,
    width=420.0,
    height=81.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("up_button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=nextPage,
    relief="flat"
)
button_2.place(
    x=824.0,
    y=637.0,
    width=174.2916717529297,
    height=80.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("up_entry_1.png"))
entry_bg_1 = canvas.create_image(
    766.0,
    372.2620048522949,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=5
)
entry_1.place(
    x=561.0,
    y=337.4803466796875,
    width=410.0,
    height=67.56331634521484
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("up_entry_2.png"))
entry_bg_2 = canvas.create_image(
    766.0,
    472.7816581726074,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=5
)
entry_2.place(
    x=561.0,
    y=438.0,
    width=410.0,
    height=67.56331634521484
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("up_entry_3.png"))
entry_bg_3 = canvas.create_image(
    766.0,
    271.7816581726074,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=5
)

entry_3.place(
    x=561.0,
    y=237.0,
    width=410.0,
    height=67.56331634521484
)

image_image_4 = PhotoImage(
    file=relative_to_assets("up_image_4.png"))
image_4 = canvas.create_image(
    509.0,
    270.0,
    image=image_image_4
)

canvas.create_text(
    501.0,
    658.0,
    anchor="nw",
    text="ALREADY HAVE ACCOUNT?",
    fill="#FFFFFF",
    font=("Montserrat SemiBold", 16 * -1)
)



a= Database.add_row('accounts', 'user1' , '12345678')
window.resizable(False, False)
window.mainloop()
